### ISSUE TITLE
Snags from TGIK

### ISSUE THREAD

**Issue by jbeda** [brendandburns/configula#5]
Hi a few snags with TGIK.

1. The link to the download was broken. Had to go to releases tab. Having it in homebrew would be awesome.
2. Not clear that I have to be in the configula git repo to get the runtime package.  Not sure how to handle that dependency but that was non-obvious to me starting out.
3. python2? python3?  I didn't have pyyaml installed and that dependency wasn't called out.
4. python installs are pretty brittle.  I had just upgraded to catalina and I think that might have busted my install. Had to reinstall python and such.
5. Shipping this as a docker container for kicking the tires might be useful.  

Video -- I did configula second: https://tgik.io/102

**Comment by brendandburns** [comment]
Thanks for the feedback @jbeda I will work on all of these.

**Comment by brendandburns** [comment]
I added a Docker image and instructions in the README. I think all of these issues are now covered. I'm going to close this issue. Please reopen (or file new issues) if you find more problems.

Thanks again!
